### ISSUE TITLE
Convert current code base to Typescript standards

### ISSUE THREAD

**Issue by raresboza** [giobiba/discordbot#4]

**Comment by giobiba** [comment]
https://github.com/giobiba/discordbot/commit/8646b5e5661ed9815f577c4f7d0262b76bad479c
Converted the project structure to typescript. I still need to rewrite the code to be in line with the typescript standard

**Comment by raresboza** [comment]
Reopened because of additional tasks

- [x]  add new linter
- [x] fix code to linter standards
- [x] adapt code to typescript standards
- [x] reenable precommit hook
