### ISSUE TITLE
Design preliminary music queue flow to gather feedback

### ISSUE THREAD

**Issue by raresboza** [giobiba/discordbot#6]

**Comment by giobiba** [comment]
- [x] create a class (called StreamDispatcher) to interface the discordjs/voice classes that play music (VoiceConnection and AudioPlayer)
- [x] create the GuildQueue class
- [x] Integrate event handling between music commands and GuildQueue
- [x] create a Search class that manipulates queries and turns them into Tracks / Lists of Tracks

**Comment by giobiba** [comment]
a temporary solution to the search class has been implemented in the play command. The class should be done in another issue
